DROP TABLE FILES;

CREATE TABLE FILES
(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
postID INT,
OWNER_USERNAME VARCHAR(255),
FILE_NAME VARCHAR(255),
FILE_TYPE VARCHAR(255),
FILE_SIZE BIGINT,
FILE_CONTENTS BLOB);
